name: chip_navigation_bar
description: A highly customizable chip-style navigation bar for Flutter with smooth animations and a modern design.
version: 1.0.0
homepage: https://github.com/SamarthGarge/Chip_Navigation_Bar

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
